// BIP39 Chinese (simplified) wordlist filtering utilities for pinyin input
//
// Mirrors bip39_filter.h's shape, but candidates are looked up by their
// (toneless, lowercase) pinyin reading instead of by English letters, and
// every function returns/consumes UTF-8 Chinese words instead of English
// ones. The on-screen a-z keyboard is reused unchanged: pinyin is typed
// with the same 26 Latin letters as English BIP39 words.
//
// Toneless pinyin has heavy homophone collisions (dozens of characters can
// share the same reading), so callers should expect much larger candidate
// lists than the English filter ever produces for the same prefix length.

#ifndef BIP39_FILTER_ZH_H
#define BIP39_FILTER_ZH_H

#include "attributes.h"
#include <stdbool.h>
#include <stdint.h>

#define BIP39_ZH_WORDLIST_SIZE 2048
// Largest observed pinyin homophone group among the 2048 words is 33
// (e.g. "shi"); sized with headroom. This bounds how many candidates a
// caller ever needs to display at once (either by pinyin prefix, or by
// pinyin prefix among the still-checksum-valid last words).
#define BIP39_ZH_MAX_FILTERED_WORDS 40
// A 12-word mnemonic's last word has 7 free entropy bits, so there are
// exactly 2^7 = 128 checksum-valid last words to choose from before any
// pinyin prefix narrows them down (24-word mnemonics only have 2^3 = 8).
// This must cover the full unfiltered set, unlike
// BIP39_ZH_MAX_FILTERED_WORDS above.
#define BIP39_ZH_MAX_VALID_LAST_WORDS 128
// Longest toneless pinyin syllable among the wordlist is 6 letters
// (e.g. "zhuang").
#define BIP39_ZH_MAX_PINYIN_LEN 8

/**
 * Toneless pinyin reading for each word, indexed identically to
 * kern_bip39_zh_wordlist(). Generated by tools/gen_bip39_zh_pinyin.py into
 * bip39_zh_pinyin_data.c.
 */
extern const char *const bip39_zh_pinyin[BIP39_ZH_WORDLIST_SIZE];

/**
 * Initialize the Chinese BIP39 wordlist. Must be called before other
 * functions. Safe to call multiple times (subsequent calls are no-ops).
 * @return true on success, false on failure
 */
KERN_WARN_UNUSED_RESULT bool bip39_filter_zh_init(void);

/**
 * Get a bitmask of valid next pinyin letters for a given prefix.
 * Bit N is set if appending letter ('a' + N) would match at least one
 * word's pinyin reading.
 * @param prefix Current pinyin prefix
 * @param prefix_len Length of prefix
 * @return 26-bit mask (bits 0-25 for a-z), or 0xFFFFFFFF if wordlist not
 *         loaded
 */
KERN_WARN_UNUSED_RESULT uint32_t
bip39_filter_zh_get_valid_letters(const char *prefix, int prefix_len);

/**
 * Filter words by pinyin prefix and return matching Chinese words.
 * @param prefix Current pinyin prefix
 * @param prefix_len Length of prefix
 * @param out_words Array to receive matching UTF-8 word pointers (point
 *                  into the compiled wordlist)
 * @param max_words Maximum number of words to return
 * @return Number of words written to out_words
 */
KERN_WARN_UNUSED_RESULT int bip39_filter_zh_by_prefix(const char *prefix,
                                                      int prefix_len,
                                                      const char **out_words,
                                                      int max_words);

/**
 * Count total number of words whose pinyin matches a prefix.
 * @param prefix Current pinyin prefix
 * @param prefix_len Length of prefix
 * @return Number of matching words, or BIP39_ZH_WORDLIST_SIZE if prefix is
 *         empty
 */
KERN_WARN_UNUSED_RESULT int bip39_filter_zh_count_matches(const char *prefix,
                                                          int prefix_len);

/**
 * Get the index (0-2047) of a Chinese BIP39 word.
 * @param word UTF-8 encoded Chinese word to look up
 * @return Word index (0-2047), or -1 if not found
 */
KERN_WARN_UNUSED_RESULT int bip39_filter_zh_get_word_index(const char *word);

/**
 * Clear the cached valid last words. Call this when moving to the last word
 * position to ensure fresh calculation based on the first N-1 words.
 */
void bip39_filter_zh_clear_last_word_cache(void);

/**
 * Get all valid last words (Chinese) that produce a valid checksum given
 * the first N-1 words.
 * @param entered_words Array of first N-1 words (UTF-8, plus placeholder
 *                       for last)
 * @param word_count Total word count (12 or 24)
 * @param out_words Array to receive valid last word pointers
 * @param max_words Maximum words to return
 * @return Number of valid last words found
 */
KERN_WARN_UNUSED_RESULT int
bip39_filter_zh_get_valid_last_words(const char entered_words[24][16],
                                     int word_count, const char **out_words,
                                     int max_words);

/**
 * Get bitmask of valid keyboard letters for last word position, based on
 * the pinyin readings of the still-valid candidate words.
 * @param entered_words Array of first N-1 words (UTF-8)
 * @param word_count Total word count (12 or 24)
 * @param prefix Current pinyin prefix being typed for last word
 * @param prefix_len Length of prefix
 * @return 26-bit mask (bits 0-25 for a-z)
 */
uint32_t
bip39_filter_zh_get_valid_letters_for_last_word(const char entered_words[24][16],
                                                int word_count,
                                                const char *prefix,
                                                int prefix_len);

/**
 * Filter valid last words (Chinese) by pinyin prefix.
 * @param entered_words Array of first N-1 words (UTF-8)
 * @param word_count Total word count (12 or 24)
 * @param prefix Pinyin prefix to filter by
 * @param prefix_len Length of prefix
 * @param out_words Array to receive matching word pointers
 * @param max_words Maximum words to return
 * @return Number of matching valid last words
 */
KERN_WARN_UNUSED_RESULT int bip39_filter_zh_last_word_by_prefix(
    const char entered_words[24][16], int word_count, const char *prefix,
    int prefix_len, const char **out_words, int max_words);

#endif // BIP39_FILTER_ZH_H
