/* Generated by tools/bake_bip39_zh_font.py -- do not edit.
 * Looks up the BIP39-Chinese-wordlist subset font closest to a UI text
 * size, for chaining into a label's font .fallback (see main/ui/theme.c).
 */
#ifndef BIP39_ZH_FONTS_H
#define BIP39_ZH_FONTS_H

#include <stddef.h>
#include <stdint.h>

#include "bip39_zh_16.h"
#include "bip39_zh_32.h"

static inline const lv_font_t *bip39_zh_font_for_size(uint16_t size) {
  static const uint16_t sizes[] = {16, 32};
  static const lv_font_t *const fonts[] = {&bip39_zh_16, &bip39_zh_32};
  size_t best = 0;
  int best_diff = -1;
  for (size_t i = 0; i < sizeof(sizes) / sizeof(sizes[0]); i++) {
    int diff = (int)sizes[i] - (int)size;
    if (diff < 0)
      diff = -diff;
    if (best_diff < 0 || diff < best_diff) {
      best_diff = diff;
      best = i;
    }
  }
  return fonts[best];
}

#endif // BIP39_ZH_FONTS_H
